sudo: false
language: python
python:
  - "2.7"
install:
  - pip install django
  - pip install -U pip
  - pip install -r requirements.txt
  - cp toutatis/config.json.sample toutatis/config.json
script:
  - ./manage.py migrate
